import { mkdir, writeFile, readFile, rm, rename, unlink, readdir } from "node:fs/promises"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { existsSync } from "node:fs"

const SCHEMA_VERSION = 2
const MAX_HISTORY = 10
const MAX_STRING_LENGTH = 50000
const MAX_ARRAY_ITEMS = 1000
const MAX_SANITIZED_LENGTH = 10000

const { deepMerge } = (() => {
  function deepMerge(existing, incoming) {
    return {
      version: SCHEMA_VERSION,
      updatedAt: new Date().toISOString(),
      task: {
        title: incoming?.task?.title ?? existing?.task?.title,
        objective: incoming?.task?.objective ?? existing?.task?.objective,
        status: incoming?.task?.status ?? existing?.task?.status ?? "in_progress",
      },
      summary: incoming?.summary ?? existing?.summary,
      currentPlan: incoming?.currentPlan ?? existing?.currentPlan ?? [],
      completedSteps: incoming?.completedSteps ?? existing?.completedSteps ?? [],
      nextSteps: incoming?.nextSteps ?? existing?.nextSteps ?? [],
      blockers: incoming?.blockers ?? existing?.blockers ?? [],
      filesTouched: incoming?.filesTouched ?? existing?.filesTouched ?? [],
      notes: incoming?.notes ?? existing?.notes ?? [],
    }
  }
  return { deepMerge }
})()

function sanitizeForMarkdown(s) {
  if (typeof s !== "string") return ""
  return s.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")
}

function sanitizeArrayForMarkdown(arr) {
  if (!arr) return []
  return arr.map((s) => sanitizeForMarkdown(s))
}

function generateHandoffMarkdown(data) {
  const title = sanitizeForMarkdown(data.task?.title ?? "Untitled Task")
  const status = sanitizeForMarkdown(data.task?.status ?? "unknown")
  const updatedAt = sanitizeForMarkdown(data.updatedAt ?? "Unknown")
  const objective = sanitizeForMarkdown(data.task?.objective ?? "Not set")
  const summary = sanitizeForMarkdown(data.summary ?? "No summary recorded.")

  const sanitizedPlan = sanitizeArrayForMarkdown(data.currentPlan)
  const sanitizedCompleted = sanitizeArrayForMarkdown(data.completedSteps)
  const sanitizedNext = sanitizeArrayForMarkdown(data.nextSteps)
  const sanitizedBlockers = sanitizeArrayForMarkdown(data.blockers)
  const sanitizedFiles = sanitizeArrayForMarkdown(data.filesTouched)
  const sanitizedNotes = sanitizeArrayForMarkdown(data.notes)

  const currentPlan =
    sanitizedPlan.length > 0
      ? sanitizedPlan.map((s, i) => `${i + 1}. ${s}`).join("\n")
      : "None recorded."

  const completedSteps =
    sanitizedCompleted.length > 0
      ? sanitizedCompleted.map((s) => `- [x] ${s}`).join("\n")
      : "None."

  const nextSteps =
    sanitizedNext.length > 0
      ? sanitizedNext.map((s) => `- [ ] ${s}`).join("\n")
      : "None."

  const blockers =
    sanitizedBlockers.length > 0
      ? sanitizedBlockers.map((b) => `- ⚠️ ${b}`).join("\n")
      : "None."

  const filesTouched =
    sanitizedFiles.length > 0
      ? sanitizedFiles.map((f) => `- 📄 ${f}`).join("\n")
      : "None recorded."

  const notes =
    sanitizedNotes.length > 0
      ? sanitizedNotes.map((n) => `- ${n}`).join("\n")
      : "None."

  return `# Handoff — ${title}

**Status:** ${status}
**Updated:** ${updatedAt}
**Objective:** ${objective}

## Summary
${summary}

## Current Plan
${currentPlan}

## Completed Steps
${completedSteps}

## Next Steps
${nextSteps}

## Blockers
${blockers}

## Files Touched
${filesTouched}

## Notes
${notes}

---
*Generated by @gitdamnit/checkpoint-orchestrator. Do not edit manually.*
*To continue: load this file and call \`checkpoint_load\` to restore full JSON state.*
`
}

function clampString(s, max) {
  if (typeof s !== "string") return undefined
  return s.length > max ? s.slice(0, max) : s
}

function clampArray(a, max) {
  if (!Array.isArray(a)) return undefined
  return a.length > max ? a.slice(0, max) : a
}

// ============================================================
// HELPERS
// ============================================================
let passed = 0
let failed = 0

function assert(desc, ok) {
  if (ok) { passed++; console.log(`  PASS: ${desc}`) }
  else { failed++; console.error(`  FAIL: ${desc}`) }
}

async function tmpDir() {
  const dir = join(tmpdir(), "cp-comp-" + Date.now() + "-" + Math.random().toString(36).slice(2))
  await mkdir(dir, { recursive: true })
  return dir
}

function randomString(len) {
  let s = ""
  const chars = "abcABC123 \t\n!@#$%^&*()_+-=[]{}|;':\",./<>?~`" + "\\"
  for (let i = 0; i < len; i++) s += chars[Math.floor(Math.random() * chars.length)]
  return s
}

function randomArray(len) {
  const arr = []
  for (let i = 0; i < len; i++) arr.push(randomString(1 + Math.floor(Math.random() * 20)))
  return arr
}

// ============================================================
// PART 1: PROPERTY-BASED FUZZ (100 iterations × many ops)
// ============================================================
function testPropertyFuzz() {
  const statuses = ["not_started", "in_progress", "blocked", "done", undefined, null]

  for (let i = 0; i < 100; i++) {
    const title = i % 10 === 0 ? undefined : randomString(Math.floor(Math.random() * 30))
    const status = statuses[Math.floor(Math.random() * statuses.length)]
    const summary = i % 7 === 0 ? null : randomString(Math.floor(Math.random() * 50))
    const planLen = Math.floor(Math.random() * 20)
    const plan = i % 5 === 0 ? null : randomArray(planLen)

    const result = deepMerge(null, {
      task: { title, status },
      summary,
      currentPlan: plan,
    })

    assert(`fuzz[${i}]: result defined`, result !== null && result !== undefined)
    assert(`fuzz[${i}]: version is ${SCHEMA_VERSION}`, result.version === SCHEMA_VERSION)
    assert(`fuzz[${i}]: updatedAt is string`, typeof result.updatedAt === "string")

    if (title !== undefined && title !== null) {
      assert(`fuzz[${i}]: title preserved`, result.task.title === title)
    }

    // Deep merge with incoming
    const title2 = randomString(10)
    const result2 = deepMerge(result, { task: { title: title2 } })
    assert(`fuzz[${i}]: deep merge overwrites title`, result2.task.title === title2)
    if (summary !== undefined && summary !== null) {
      assert(`fuzz[${i}]: deep merge keeps summary`, result2.summary === summary)
    }
  }
}
testPropertyFuzz()

// ============================================================
// PART 2: FILESYSTEM INTEGRATION — FULL LIFECYCLE
// ============================================================

async function testFullLifecycle() {
  const dir = await tmpDir()
  const file = join(dir, "checkpoint.json")
  const historyFile = join(dir, "checkpoint-history.json")
  const handoffFile = join(dir, "handoff.md")

  async function save(data, snapshotName) {
    const merged = deepMerge(null, data)
    await mkdir(dir, { recursive: true })
    const tmp = file + ".tmp." + Date.now()
    await writeFile(tmp, JSON.stringify(merged, null, 2), "utf8")
    await rename(tmp, file)
    const handoffTmp = handoffFile + ".tmp." + Date.now()
    await writeFile(handoffTmp, generateHandoffMarkdown(merged), "utf8")
    await rename(handoffTmp, handoffFile)
    const history = JSON.parse(await readFile(historyFile, "utf8").catch(() => '{"snapshots":[]}'))
    history.snapshots.push({
      name: snapshotName ?? `auto-${Date.now()}`,
      savedAt: new Date().toISOString(),
      data: JSON.parse(JSON.stringify(merged)),
    })
    if (history.snapshots.length > MAX_HISTORY) history.snapshots = history.snapshots.slice(-MAX_HISTORY)
    const hTmp = historyFile + ".tmp." + Date.now()
    await writeFile(hTmp, JSON.stringify(history, null, 2), "utf8")
    await rename(hTmp, historyFile)
    return merged
  }

  // Save initial
  const r1 = await save({ task: { title: "Integration Test", status: "in_progress" } })
  assert("lifecycle: save creates checkpoint.json", existsSync(file))
  assert("lifecycle: save creates handoff.md", existsSync(handoffFile))
  assert("lifecycle: save creates history.json", existsSync(historyFile))
  assert("lifecycle: checkpoint has title", r1.task.title === "Integration Test")

  // Load
  const loaded = JSON.parse(await readFile(file, "utf8"))
  assert("lifecycle: load returns correct title", loaded.task.title === "Integration Test")
  assert("lifecycle: load has version", loaded.version === SCHEMA_VERSION)

  // Handoff content
  const handoff = await readFile(handoffFile, "utf8")
  assert("lifecycle: handoff contains title", handoff.includes("Integration Test"))
  assert("lifecycle: handoff contains footer", handoff.includes("@gitdamnit/checkpoint-orchestrator"))

  // Clear (simulate)
  for (const f of [file, handoffFile, historyFile]) {
    await unlink(f).catch(() => {})
  }
  assert("lifecycle: checkpoint deleted", !existsSync(file))
  assert("lifecycle: handoff deleted", !existsSync(handoffFile))
  assert("lifecycle: history deleted", !existsSync(historyFile))

  await rm(dir, { recursive: true, force: true })
}
await testFullLifecycle()

async function testMultipleSequentialSaves() {
  const dir = await tmpDir()
  const file = join(dir, "checkpoint.json")
  const historyFile = join(dir, "checkpoint-history.json")
  const handoffFile = join(dir, "handoff.md")

  let state = null
  const titles = ["First", "Second", "Third", "Fourth", "Fifth"]
  for (const title of titles) {
    const merged = deepMerge(state, { task: { title } })
    await mkdir(dir, { recursive: true })
    const tmp = file + ".tmp." + Date.now()
    await writeFile(tmp, JSON.stringify(merged, null, 2), "utf8")
    await rename(tmp, file)
    const hTmp = handoffFile + ".tmp." + Date.now()
    await writeFile(hTmp, generateHandoffMarkdown(merged), "utf8")
    await rename(hTmp, handoffFile)
    state = merged
  }

  const final = JSON.parse(await readFile(file, "utf8"))
  assert("sequential: last title wins", final.task.title === "Fifth")
  assert("sequential: version correct", final.version === SCHEMA_VERSION)

  await rm(dir, { recursive: true, force: true })
}
await testMultipleSequentialSaves()

// ============================================================
// PART 3: RECOVERY & RESILIENCE
// ============================================================

async function testCorruptedCheckpoint() {
  const dir = await tmpDir()
  const file = join(dir, "checkpoint.json")
  await writeFile(file, "this is not valid json{broken")
  const loaded = await (async () => {
    try { return JSON.parse(await readFile(file, "utf8")) }
    catch { return null }
  })()
  assert("recovery: corrupted json returns null", loaded === null)
  await rm(dir, { recursive: true, force: true })
}
await testCorruptedCheckpoint()

async function testCorruptedHistory() {
  const dir = await tmpDir()
  const historyFile = join(dir, "checkpoint-history.json")
  await writeFile(historyFile, "{{{broken")
  const loaded = await (async () => {
    try { return JSON.parse(await readFile(historyFile, "utf8")) }
    catch { return { snapshots: [] } }
  })()
  assert("recovery: corrupted history returns empty", Array.isArray(loaded.snapshots))
  assert("recovery: corrupted history has 0 snapshots", loaded.snapshots.length === 0)
  await rm(dir, { recursive: true, force: true })
}
await testCorruptedHistory()

async function testMissingDirThenSave() {
  const dir = await tmpDir()
  await rm(dir, { recursive: true, force: true })
  // dir no longer exists
  const file = join(dir, "checkpoint.json")
  let saved = false
  try {
    await mkdir(dir, { recursive: true })
    await writeFile(file, JSON.stringify({ version: SCHEMA_VERSION, updatedAt: new Date().toISOString(), task: { title: "After mkdir" } }))
    saved = true
  } catch {}
  assert("recovery: save after mkdir succeeds", saved)
  if (saved) {
    const loaded = JSON.parse(await readFile(file, "utf8"))
    assert("recovery: data intact after mkdir", loaded.task.title === "After mkdir")
  }
  await rm(dir, { recursive: true, force: true }).catch(() => {})
}
await testMissingDirThenSave()

async function testEmptyStateFile() {
  const dir = await tmpDir()
  const file = join(dir, "checkpoint.json")
  await writeFile(file, "", "utf8")
  const loaded = await (async () => {
    try { return JSON.parse(await readFile(file, "utf8")) }
    catch { return null }
  })()
  assert("recovery: empty file returns null", loaded === null)
  await rm(dir, { recursive: true, force: true })
}
await testEmptyStateFile()

async function testMissingHandoffIsRegenerated() {
  const dir = await tmpDir()
  const file = join(dir, "checkpoint.json")
  const handoffFile = join(dir, "handoff.md")

  // Write checkpoint but no handoff
  await writeFile(file, JSON.stringify({ version: SCHEMA_VERSION, updatedAt: new Date().toISOString(), task: { title: "No handoff" } }), "utf8")
  assert("recovery: handoff missing initially", !existsSync(handoffFile))

  // Regenerate on save
  const merged = JSON.parse(await readFile(file, "utf8"))
  const hTmp = handoffFile + ".tmp." + Date.now()
  await writeFile(hTmp, generateHandoffMarkdown(merged), "utf8")
  await rename(hTmp, handoffFile)
  assert("recovery: handoff regenerated", existsSync(handoffFile))
  const handoff = await readFile(handoffFile, "utf8")
  assert("recovery: regenerated handoff has title", handoff.includes("No handoff"))

  await rm(dir, { recursive: true, force: true })
}
await testMissingHandoffIsRegenerated()

async function testPartialWriteCrash() {
  const dir = await tmpDir()
  const file = join(dir, "checkpoint.json")
  const historyFile = join(dir, "checkpoint-history.json")

  // Simulate: old valid data exists, then crash mid-write
  await writeFile(file, JSON.stringify({ version: SCHEMA_VERSION, updatedAt: new Date().toISOString(), task: { title: "Before crash" } }), "utf8")

  // Atomic write crash simulation: write tmp file but crash before rename
  const tmp = file + ".tmp." + Date.now()
  await writeFile(tmp, JSON.stringify({ version: SCHEMA_VERSION, updatedAt: new Date().toISOString(), task: { title: "Crash data" } }), "utf8")
  // crash happens — rename never called

  // Original file should still be intact
  const loaded = JSON.parse(await readFile(file, "utf8"))
  assert("recovery: original intact after crash", loaded.task.title === "Before crash")
  assert("recovery: temp file NOT the main file", !file.includes(".tmp."))

  await rm(dir, { recursive: true, force: true })
}
await testPartialWriteCrash()

// ============================================================
// PART 4: ATOMIC WRITE VERIFICATION
// ============================================================

async function testAtomicTempFileUniqueness() {
  const dir = await tmpDir()
  const file = join(dir, "checkpoint.json")
  const tmpFiles = new Set()

  for (let i = 0; i < 50; i++) {
    const tmp = file + ".tmp." + Date.now() + "-" + i
    tmpFiles.add(tmp)
    await writeFile(tmp, JSON.stringify({ version: SCHEMA_VERSION, updatedAt: new Date().toISOString(), task: { title: `save-${i}` } }), "utf8")
    await rename(tmp, file)
  }

  assert("atomic: all temp filenames unique", tmpFiles.size === 50)
  const final = JSON.parse(await readFile(file, "utf8"))
  assert("atomic: final save valid", final.version === SCHEMA_VERSION)

  // No temp files left behind
  const entries = await readdir(dir)
  const leftovers = entries.filter(e => e.includes(".tmp."))
  assert("atomic: zero temp file leftovers", leftovers.length === 0)

  await rm(dir, { recursive: true, force: true })
}
await testAtomicTempFileUniqueness()

async function testAtomicRenameIsDataComplete() {
  const dir = await tmpDir()
  const file = join(dir, "checkpoint.json")
  const largeData = {
    version: SCHEMA_VERSION,
    updatedAt: new Date().toISOString(),
    task: { title: "Large", objective: "x".repeat(10000), status: "in_progress" },
    summary: "y".repeat(10000),
    currentPlan: new Array(500).fill("plan item"),
    notes: new Array(500).fill("note item"),
  }

  const tmp = file + ".tmp." + Date.now()
  await writeFile(tmp, JSON.stringify(largeData, null, 2), "utf8")
  await rename(tmp, file)

  const loaded = JSON.parse(await readFile(file, "utf8"))
  assert("atomic: large data objective length", loaded.task.objective.length === 10000)
  assert("atomic: large data plan count", loaded.currentPlan.length === 500)

  await rm(dir, { recursive: true, force: true })
}
await testAtomicRenameIsDataComplete()

// ============================================================
// PART 5: RING BUFFER HISTORY
// ============================================================

function testRingBufferExactBoundary() {
  const snapshots = []
  for (let i = 1; i <= MAX_HISTORY; i++) snapshots.push({ name: `s-${i}` })
  assert("ring: exactly MAX_HISTORY stays", snapshots.slice(-MAX_HISTORY).length === MAX_HISTORY)
  assert("ring: first element still s-1", snapshots.slice(-MAX_HISTORY)[0].name === "s-1")

  snapshots.push({ name: "s-11" })
  const pruned = snapshots.slice(-MAX_HISTORY)
  assert("ring: +1 prunes oldest", pruned[0].name === "s-2")
  assert("ring: +1 keeps newest", pruned[pruned.length - 1].name === "s-11")

  // Push 5 more
  for (let i = 12; i <= 15; i++) snapshots.push({ name: `s-${i}` })
  const pruned2 = snapshots.slice(-MAX_HISTORY)
  assert("ring: +5 total prunes to 10", pruned2.length === MAX_HISTORY)
  assert("ring: oldest is s-6", pruned2[0].name === "s-6")
  assert("ring: newest is s-15", pruned2[MAX_HISTORY - 1].name === "s-15")
}
testRingBufferExactBoundary()

function testRingBufferEmptyAndSingle() {
  const empty = []
  assert("ring: empty stays empty", empty.slice(-MAX_HISTORY).length === 0)

  const single = [{ name: "only" }]
  const pruned = single.slice(-MAX_HISTORY)
  assert("ring: single preserved", pruned.length === 1)
  assert("ring: single name correct", pruned[0].name === "only")
}
testRingBufferEmptyAndSingle()

function testNamedVsAutoSnapshots() {
  const named = "my-manual-save"
  const auto = `auto-${Date.now()}`
  assert("ring: named snapshot starts with custom", named === "my-manual-save")
  assert("ring: auto snapshot starts with auto-", auto.startsWith("auto-"))
  const ts = Number(auto.split("auto-")[1])
  assert("ring: auto timestamp is number", !isNaN(ts))
  assert("ring: auto timestamp recent", ts > Date.now() - 60000)
}
testNamedVsAutoSnapshots()

function testHistoryNewestFirstOrdering() {
  const snapshots = []
  for (let i = 1; i <= 5; i++) snapshots.push({ name: `snap-${i}`, savedAt: `2026-01-0${i}T00:00:00.000Z` })
  const reversed = [...snapshots].reverse()
  assert("ring: newest first is snap-5", reversed[0].name === "snap-5")
  assert("ring: index 1 is snap-4", reversed[1].name === "snap-4")
  assert("ring: index 2 is snap-3", reversed[2].name === "snap-3")
  assert("ring: oldest last is snap-1", reversed[4].name === "snap-1")
  assert("ring: count preserved", reversed.length === 5)
}
testHistoryNewestFirstOrdering()

// ============================================================
// PART 6: DEEP MERGE COMBINATORIAL
// ============================================================

function testDeepMergeAllStatusTransitions() {
  const statuses = ["not_started", "in_progress", "blocked", "done"]
  for (const from of statuses) {
    for (const to of statuses) {
      const first = deepMerge(null, { task: { status: from } })
      assert(`merge: ${from}->${to} initial`, first.task.status === from)
      const second = deepMerge(first, { task: { status: to } })
      assert(`merge: ${from}->${to} transition`, second.task.status === to)
    }
  }
}
testDeepMergeAllStatusTransitions()

function testDeepMergeAllFieldTypes() {
  // Each field type individually
  const title = deepMerge(null, { task: { title: "Title Only" } })
  assert("merge: title only", title.task.title === "Title Only")

  const objective = deepMerge(null, { task: { objective: "Objective Only" } })
  assert("merge: objective only", objective.task.objective === "Objective Only")

  const summary = deepMerge(null, { summary: "Summary Only" })
  assert("merge: summary only", summary.summary === "Summary Only")

  const plan = deepMerge(null, { currentPlan: ["A", "B"] })
  assert("merge: plan only", plan.currentPlan.length === 2)

  const steps = deepMerge(null, { completedSteps: ["X"] })
  assert("merge: completed only", steps.completedSteps[0] === "X")

  const next = deepMerge(null, { nextSteps: ["Y"] })
  assert("merge: next only", next.nextSteps[0] === "Y")

  const blockers = deepMerge(null, { blockers: ["Z"] })
  assert("merge: blockers only", blockers.blockers[0] === "Z")

  const files = deepMerge(null, { filesTouched: ["a.ts"] })
  assert("merge: files only", files.filesTouched[0] === "a.ts")

  const notes = deepMerge(null, { notes: ["Note"] })
  assert("merge: notes only", notes.notes[0] === "Note")
}
testDeepMergeAllFieldTypes()

function testDeepMergePartialUpdatesPreserveOtherFields() {
  const full = deepMerge(null, {
    task: { title: "Full", objective: "Do it", status: "in_progress" },
    summary: "S",
    currentPlan: ["A"],
    completedSteps: ["B"],
    nextSteps: ["C"],
    blockers: ["D"],
    filesTouched: ["E"],
    notes: ["F"],
  })

  // Update only status
  const partial = deepMerge(full, { task: { status: "done" } })
  assert("merge: partial keeps title", partial.task.title === "Full")
  assert("merge: partial keeps objective", partial.task.objective === "Do it")
  assert("merge: partial updates status", partial.task.status === "done")
  assert("merge: partial keeps summary", partial.summary === "S")
  assert("merge: partial keeps plan", partial.currentPlan[0] === "A")
  assert("merge: partial keeps completed", partial.completedSteps[0] === "B")
  assert("merge: partial keeps next", partial.nextSteps[0] === "C")
  assert("merge: partial keeps blockers", partial.blockers[0] === "D")
  assert("merge: partial keeps files", partial.filesTouched[0] === "E")
  assert("merge: partial keeps notes", partial.notes[0] === "F")
}
testDeepMergePartialUpdatesPreserveOtherFields()

function testDeepMergeEmptyStringPreservation() {
  const withEmpty = deepMerge(null, {
    task: { title: "", objective: "", status: "in_progress" },
    summary: "",
    currentPlan: [],
    completedSteps: [],
    nextSteps: [],
    blockers: [],
    filesTouched: [],
    notes: [],
  })
  assert("merge: empty title preserved", withEmpty.task.title === "")
  assert("merge: empty objective preserved", withEmpty.task.objective === "")
  assert("merge: empty summary preserved", withEmpty.summary === "")
  assert("merge: empty plan is array", Array.isArray(withEmpty.currentPlan))
  assert("merge: empty plan length 0", withEmpty.currentPlan.length === 0)
}
testDeepMergeEmptyStringPreservation()

function testDeepMergeNullPreservation() {
  const result = deepMerge(null, {
    task: null,
    summary: null,
    currentPlan: null,
    completedSteps: null,
    nextSteps: null,
    blockers: null,
    filesTouched: null,
    notes: null,
  })
  assert("merge: null task becomes object", typeof result.task === "object")
  assert("merge: null summary undefined", result.summary === undefined)
  assert("merge: null plan defaults to []", Array.isArray(result.currentPlan))
}
testDeepMergeNullPreservation()

function testDeepMergeChainPreservesArrays() {
  let state = deepMerge(null, { currentPlan: ["Step 1", "Step 2"] })
  state = deepMerge(state, { completedSteps: ["Step 1"] })
  state = deepMerge(state, { blockers: ["Waiting"] })
  assert("merge: chain plan intact", state.currentPlan[1] === "Step 2")
  assert("merge: chain completed intact", state.completedSteps[0] === "Step 1")
  assert("merge: chain blockers intact", state.blockers[0] === "Waiting")
}
testDeepMergeChainPreservesArrays()

// ============================================================
// PART 7: SANITIZATION COMPREHENSIVE
// ============================================================

function testSanitizeAllSpecialChars() {
  const cases = [
    ["<script>", "&lt;script&gt;"],
    ["<img src=x onerror=alert(1)>", "&lt;img src=x onerror=alert(1)&gt;"],
    ["a<b>c", "a&lt;b&gt;c"],
    [">>>", "&gt;&gt;&gt;"],
    ["<<<", "&lt;&lt;&lt;"],
    ["<a href=\"javascript:alert(1)\">click</a>", "&lt;a href=&quot;javascript:alert(1)&quot;&gt;click&lt;/a&gt;"],
  ]

  for (const [input, expected] of cases) {
    const result = sanitizeForMarkdown(input)
    assert(`sanitize: ${input.slice(0, 20)} -> ${expected.slice(0, 20)}`, result === expected)
  }
}
testSanitizeAllSpecialChars()

function testSanitizeBoundaries() {
  assert("sanitize: undefined returns empty", sanitizeForMarkdown(undefined) === "")
  assert("sanitize: null returns empty", sanitizeForMarkdown(null) === "")
  assert("sanitize: number returns empty", sanitizeForMarkdown(123) === "")
  assert("sanitize: empty string returns empty", sanitizeForMarkdown("") === "")
  assert("sanitize: no-angle text unchanged", sanitizeForMarkdown("hello world") === "hello world")
  assert("sanitize: already escaped preserved", sanitizeForMarkdown("&lt;") === "&lt;")
}
testSanitizeBoundaries()

function testSanitizeArray() {
  assert("sanitizeArr: undefined returns []", sanitizeArrayForMarkdown(undefined).length === 0)
  assert("sanitizeArr: null returns []", sanitizeArrayForMarkdown(null).length === 0)
  assert("sanitizeArr: empty returns []", sanitizeArrayForMarkdown([]).length === 0)

  const result = sanitizeArrayForMarkdown(["<a>", "b", "<script>alert(1)</script>"])
  assert("sanitizeArr: escapes <a>", result[0] === "&lt;a&gt;")
  assert("sanitizeArr: keeps b", result[1] === "b")
  assert("sanitizeArr: escapes script", result[2] === "&lt;script&gt;alert(1)&lt;/script&gt;")
}
testSanitizeArray()

function testSanitizeUnicode() {
  const cases = ["🔥", "中文", "日本語", "éèêë", "ñçö", "\u0000null", "\uFFFFmax"]
  for (const c of cases) {
    assert(`sanitize: unicode '${c.slice(0, 10)}' preserved`, sanitizeForMarkdown(c) === c)
  }
}
testSanitizeUnicode()

function testHandoffSanitization() {
  const data = {
    version: 2,
    updatedAt: new Date().toISOString(),
    task: { title: "<script>alert('xss')</script>", status: "in_progress", objective: "<img src=x>" },
    summary: "<a href='evil'>link</a>",
    notes: ["<b>bold</b>", "<script>evil</script>"],
    currentPlan: ["step < 3"],
    completedSteps: ["done > 5"],
  }
  const md = generateHandoffMarkdown(data)
  assert("handoff: script escaped", md.includes("&lt;script&gt;alert('xss')&lt;/script&gt;"))
  assert("handoff: img escaped", md.includes("&lt;img src=x&gt;"))
  assert("handoff: anchor escaped", md.includes("&lt;a href='evil'&gt;link&lt;/a&gt;"))
  assert("handoff: note escaped", md.includes("&lt;b&gt;bold&lt;/b&gt;"))
  assert("handoff: plan angle escaped", md.includes("step &lt; 3"))
  assert("handoff: completed angle escaped", md.includes("done &gt; 5"))
  assert("handoff: no raw angle brackets", !md.includes("<script>") && !md.includes("<img"))
}
testHandoffSanitization()

// ============================================================
// PART 8: CLAMP BOUNDARY TESTS
// ============================================================

function testClampStringBoundaries() {
  assert("clamp: undefined returns undefined", clampString(undefined, 10) === undefined)
  assert("clamp: null returns undefined", clampString(null, 10) === undefined)
  assert("clamp: number returns undefined", clampString(123, 10) === undefined)
  assert("clamp: empty string preserved", clampString("", 10) === "")
  assert("clamp: short string preserved", clampString("hello", 10) === "hello")
  assert("clamp: exact boundary preserved", clampString("1234567890", 10) === "1234567890")
  assert("clamp: one over truncates", clampString("1234567890A", 10) === "1234567890")
  assert("clamp: way over truncates", clampString("x".repeat(1000), 10) === "x".repeat(10))
  assert("clamp: max string correct", clampString("x".repeat(MAX_STRING_LENGTH), MAX_STRING_LENGTH).length === MAX_STRING_LENGTH)
  assert("clamp: max+1 truncated", clampString("x".repeat(MAX_STRING_LENGTH + 1), MAX_STRING_LENGTH).length === MAX_STRING_LENGTH)
}
testClampStringBoundaries()

function testClampArrayBoundaries() {
  assert("clampArr: undefined returns undefined", clampArray(undefined, 10) === undefined)
  assert("clampArr: null returns undefined", clampArray(null, 10) === undefined)
  assert("clampArr: string returns undefined", clampArray("not array", 10) === undefined)
  assert("clampArr: empty preserved", clampArray([], 10).length === 0)
  assert("clampArr: small preserved", clampArray(["a", "b"], 10).length === 2)
  assert("clampArr: exact boundary", clampArray(new Array(10).fill("x"), 10).length === 10)
  assert("clampArr: one over truncates", clampArray(new Array(11).fill("x"), 10).length === 10)
  assert("clampArr: way over truncates", clampArray(new Array(1000).fill("x"), 10).length === 10)
  assert("clampArr: max items correct", clampArray(new Array(MAX_ARRAY_ITEMS).fill("x"), MAX_ARRAY_ITEMS).length === MAX_ARRAY_ITEMS)
  assert("clampArr: max+1 truncated", clampArray(new Array(MAX_ARRAY_ITEMS + 1).fill("x"), MAX_ARRAY_ITEMS).length === MAX_ARRAY_ITEMS)
}
testClampArrayBoundaries()

// ============================================================
// PART 9: SCHEMA VERSION HANDLING
// ============================================================

function testSchemaVersionDetection() {
  assert("schema: current version", SCHEMA_VERSION === 2)
  assert("schema: v1 detected as old", 1 < SCHEMA_VERSION)
  assert("schema: v3 detected as future", 3 > SCHEMA_VERSION)
  assert("schema: v2 is current", !(SCHEMA_VERSION < SCHEMA_VERSION))
}
testSchemaVersionDetection()

function testSchemaMigrationFromV1() {
  const v1Data = { version: 1, updatedAt: "2025-01-01T00:00:00.000Z", task: { title: "Legacy", status: "in_progress" } }
  const merged = deepMerge(v1Data, { task: { objective: "Migrate" } })
  assert("schema: v1 merged gets v2", merged.version === SCHEMA_VERSION)
  assert("schema: v1 title preserved", merged.task.title === "Legacy")
  assert("schema: v1 merged keeps objective", merged.task.objective === "Migrate")
}
testSchemaMigrationFromV1()

function testSchemaVersionZero() {
  const v0 = { version: 0, task: { title: "Alpha" } }
  assert("schema: v0 is old", 0 < SCHEMA_VERSION)
  const merged = deepMerge(v0, { summary: "Migrated from v0" })
  assert("schema: v0 merged version", merged.version === SCHEMA_VERSION)
  assert("schema: v0 title preserved", merged.task.title === "Alpha")
}
testSchemaVersionZero()

function testSchemaMissingVersion() {
  const noVer = { task: { title: "No version" } }
  assert("schema: missing version undefined", noVer.version === undefined)
  const merged = deepMerge(noVer, { task: { status: "done" } })
  assert("schema: no-version merged gets v2", merged.version === SCHEMA_VERSION)
  assert("schema: no-version title preserved", merged.task.title === "No version")
}
testSchemaMissingVersion()

// ============================================================
// PART 10: TIMESTAMP & FORMAT
// ============================================================

function testTimestampFormat() {
  const result = deepMerge(null, { task: { title: "Timestamp test" } })
  const ts = result.updatedAt
  assert("timestamp: is string", typeof ts === "string")
  assert("timestamp: ISO format", /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(ts))
  assert("timestamp: has Z or offset", ts.endsWith("Z") || /[+-]\d{2}:\d{2}$/.test(ts))
  const parsed = new Date(ts)
  assert("timestamp: valid date", !isNaN(parsed.getTime()))
  assert("timestamp: recent", parsed.getTime() > Date.now() - 5000)
  assert("timestamp: not in future", parsed.getTime() <= Date.now() + 1000)
}
testTimestampFormat()

// ============================================================
// PART 11: STRESS — 1000 OPERATIONS
// ============================================================

function testStressThousandMerges() {
  let state = null
  const titles = []
  for (let i = 0; i < 1000; i++) {
    const title = `stress-${i}`
    if (i % 100 === 0) titles.push(title)
    state = deepMerge(state, {
      task: { title, status: i % 2 === 0 ? "in_progress" : "blocked" },
      completedSteps: [`step-${i}`],
      notes: [`note-${i}`],
    })
  }
  assert("stress: 1000 merges title", state.task.title === "stress-999")
  assert("stress: 1000 merges last step", state.completedSteps[0] === "step-999")
  assert("stress: 1000 merges last note", state.notes[0] === "note-999")
  assert("stress: 1000 merges last step only (?? replacement)", state.completedSteps.length === 1 && state.completedSteps[0] === "step-999")
}
testStressThousandMerges()

async function testStressThousandFileSaves() {
  const dir = await tmpDir()
  const file = join(dir, "checkpoint.json")
  const historyFile = join(dir, "checkpoint-history.json")
  const handoffFile = join(dir, "handoff.md")

  let state = null
  for (let i = 0; i < 200; i++) {
    state = deepMerge(state, {
      task: { title: `save-${i}`, status: "in_progress" },
      notes: [`iteration-${i}`],
    })
    await mkdir(dir, { recursive: true })
    const tmp = file + ".tmp." + Date.now()
    await writeFile(tmp, JSON.stringify(state, null, 2), "utf8")
    await rename(tmp, file)
    const hTmp = handoffFile + ".tmp." + Date.now()
    await writeFile(hTmp, generateHandoffMarkdown(state), "utf8")
    await rename(hTmp, handoffFile)
    const history = JSON.parse(await readFile(historyFile, "utf8").catch(() => '{"snapshots":[]}'))
    history.snapshots.push({ name: `save-${i}`, savedAt: new Date().toISOString(), data: JSON.parse(JSON.stringify(state)) })
    if (history.snapshots.length > MAX_HISTORY) history.snapshots = history.snapshots.slice(-MAX_HISTORY)
    const histTmp = historyFile + ".tmp." + Date.now()
    await writeFile(histTmp, JSON.stringify(history, null, 2), "utf8")
    await rename(histTmp, historyFile)
  }

  const loaded = JSON.parse(await readFile(file, "utf8"))
  assert("stress: 200 saves title", loaded.task.title === "save-199")
  assert("stress: 200 saves note", loaded.notes[0] === "iteration-199")

  const history = JSON.parse(await readFile(historyFile, "utf8"))
  assert("stress: history has 10 entries", history.snapshots.length === MAX_HISTORY)
  assert("stress: oldest is save-190", history.snapshots[0].name === "save-190")
  assert("stress: newest is save-199", history.snapshots[MAX_HISTORY - 1].name === "save-199")

  const entries = await readdir(dir)
  const tmpFiles = entries.filter(e => e.includes(".tmp."))
  assert("stress: zero temp file leftovers", tmpFiles.length === 0)

  await rm(dir, { recursive: true, force: true })
}
await testStressThousandFileSaves()

// ============================================================
// PART 12: SECURITY — EXTENDED VECTORS
// ============================================================

function testSecurityProtoPollutionVariants() {
  // Variant 1: __proto__
  const v1 = deepMerge(null, { __proto__: { polluted: true } })
  assert("security: __proto__ not set", !v1.polluted)
  const obj1 = {}
  assert("security: __proto__ global clean", !obj1.polluted)

  // Variant 2: constructor.prototype
  const v2 = deepMerge(null, { constructor: { prototype: { polluted: true } } })
  const obj2 = {}
  assert("security: constructor proto global clean", !obj2.polluted)

  // Variant 3: nested __proto__
  const v3 = deepMerge(null, { task: { __proto__: { polluted: true } } })
  assert("security: nested __proto__ not set", !v3.polluted)

  // Variant 4: prototype pollution in arrays
  const arrPayload = { __proto__: { polluted: true }, currentPlan: ["safe"] }
  const v4 = deepMerge(null, arrPayload)
  assert("security: array proto not set", !v4.polluted)
}
testSecurityProtoPollutionVariants()

function testSecurityDosLargeArray() {
  const huge = new Array(100000).fill("x")
  const result = deepMerge(null, { currentPlan: huge })
  assert("security: huge array preserved", result.currentPlan.length === 100000)
}
testSecurityDosLargeArray()

function testSecurityDosDeeplyNested() {
  const nested = { task: { title: "a" } }
  // Create deeply nested object in summary (though clampString would handle it in execute)
  const result = deepMerge(null, {
    task: { title: "nested" },
    notes: [JSON.stringify(nested)],
  })
  assert("security: nested note preserved", result.notes[0].includes("title"))
}
testSecurityDosDeeplyNested()

function testSecurityHandoffInjectionAllContexts() {
  const payloads = [
    { field: "summary", value: "<script>alert(1)</script>" },
    { field: "currentPlan", value: ["- [x] malicious", "> blockquote injection"] },
    { field: "notes", value: ["```\ncode block\n```", "![image](javascript:alert(1))"] },
    { field: "task.title", value: "[Click](data:text/html,<script>alert(1)</script>)" },
  ]

  for (const p of payloads) {
    const data = {
      version: 2,
      updatedAt: new Date().toISOString(),
      task: { title: "Security", status: "in_progress" },
      summary: p.field === "summary" ? p.value : "ok",
      currentPlan: p.field === "currentPlan" ? p.value : [],
      notes: p.field === "notes" ? p.value : [],
    }
    if (p.field === "task.title") data.task.title = p.value

    const md = generateHandoffMarkdown(data)
    assert(`security: handoff renders for ${p.field}`, md.includes("Security") || md.includes("&lt;"))
  }
}
testSecurityHandoffInjectionAllContexts()

// ============================================================
// PART 13: SNAPSHOT OPERATIONS
// ============================================================

function testSnapshotFindAndUndo() {
  const snapshots = [
    { name: "initial", savedAt: "2026-01-01T00:00:00.000Z", data: { version: 2, task: { title: "Initial" } } },
    { name: "midway", savedAt: "2026-01-02T00:00:00.000Z", data: { version: 2, task: { title: "Midway" } } },
    { name: "final", savedAt: "2026-01-03T00:00:00.000Z", data: { version: 2, task: { title: "Final" } } },
  ]

  const target = snapshots.find(s => s.name === "midway")
  assert("snapshot: find by name", target.name === "midway")
  assert("snapshot: found data title", target.data.task.title === "Midway")

  const unknown = snapshots.find(s => s.name === "nonexistent")
  assert("snapshot: unknown returns undefined", unknown === undefined)

  // Simulate undo: save current as pre-restore
  const liveState = { version: 2, task: { title: "Live" } }
  const preRestoreName = `pre-restore-${Date.now()}`
  snapshots.push({ name: preRestoreName, savedAt: new Date().toISOString(), data: JSON.parse(JSON.stringify(liveState)) })
  const found = snapshots.find(s => s.name === preRestoreName)
  assert("snapshot: undo point saved", found.name === preRestoreName)
  assert("snapshot: undo data correct", found.data.task.title === "Live")
}
testSnapshotFindAndUndo()

// ============================================================
// PART 14: HANDOFF OUTPUT STRUCTURE
// ============================================================

function testHandoffFullStructure() {
  const data = {
    version: 2,
    updatedAt: "2026-05-13T12:00:00.000Z",
    task: { title: "Full Test", status: "done", objective: "Test all things" },
    summary: "Everything works.",
    currentPlan: ["Plan 1", "Plan 2", "Plan 3"],
    completedSteps: ["Done 1", "Done 2"],
    nextSteps: ["Next 1"],
    blockers: ["Block 1"],
    filesTouched: ["a.ts", "b.ts", "c.ts"],
    notes: ["Remember X", "Fix Y later"],
  }

  const md = generateHandoffMarkdown(data)
  const lines = md.split("\n")

  assert("handoff: starts with H1", lines[0].startsWith("# Handoff"))
  assert("handoff: has status", lines.some(l => l.includes("**Status:**")))
  assert("handoff: has updated", lines.some(l => l.includes("**Updated:**")))
  assert("handoff: has objective", lines.some(l => l.includes("**Objective:**")))
  assert("handoff: has Summary section", lines.some(l => l === "## Summary"))
  assert("handoff: has Current Plan section", lines.some(l => l === "## Current Plan"))
  assert("handoff: has Completed Steps", lines.some(l => l === "## Completed Steps"))
  assert("handoff: has Next Steps", lines.some(l => l === "## Next Steps"))
  assert("handoff: has Blockers", lines.some(l => l === "## Blockers"))
  assert("handoff: has Files Touched", lines.some(l => l === "## Files Touched"))
  assert("handoff: has Notes", lines.some(l => l === "## Notes"))
  assert("handoff: has footer", lines.some(l => l.includes("Generated by")))
  assert("handoff: has do-not-edit", lines.some(l => l.includes("Do not edit")))
  assert("handoff: has separator", lines.some(l => l.startsWith("---")))
  assert("handoff: 3 plan items counted", (md.match(/^\d+\. /gm) || []).length === 3)
  assert("handoff: 2 completed items", (md.match(/^- \[x\] /gm) || []).length === 2)
  assert("handoff: 1 next item", (md.match(/^- \[ \] /gm) || []).length === 1)
  assert("handoff: 1 blocker", (md.match(/⚠️/g) || []).length === 1)
  assert("handoff: 3 files", (md.match(/📄/g) || []).length === 3)
  assert("handoff: 2 notes", (md.match(/^- (?!\[|⚠️|📄)/gm) || []).length >= 2)
}
testHandoffFullStructure()

function testHandoffEmptyFallbacks() {
  const data = { version: 2, updatedAt: "2026-01-01T00:00:00.000Z", task: {} }
  const md = generateHandoffMarkdown(data)
  assert("handoff: empty title fallback", md.includes("Untitled Task"))
  assert("handoff: empty status fallback", md.includes("unknown"))
  assert("handoff: empty objective fallback", md.includes("Not set"))
  assert("handoff: empty summary fallback", md.includes("No summary recorded."))
  assert("handoff: empty plan fallback", md.includes("None recorded."))
  assert("handoff: empty completed fallback", md.includes("None."))
  assert("handoff: empty next fallback", md.includes("None."))
  assert("handoff: empty blockers fallback", md.includes("None."))
  assert("handoff: empty files fallback", md.includes("None recorded."))
  assert("handoff: empty notes fallback", md.includes("None."))
}
testHandoffEmptyFallbacks()

// ============================================================
// PART 15: CHECKPOINT CLEAR (simulated)
// ============================================================

async function testCheckpointClearAllThreeFiles() {
  const dir = await tmpDir()
  const file = join(dir, "checkpoint.json")
  const historyFile = join(dir, "checkpoint-history.json")
  const handoffFile = join(dir, "handoff.md")

  // Create all three
  await writeFile(file, "{}", "utf8")
  await writeFile(historyFile, '{"snapshots":[]}', "utf8")
  await writeFile(handoffFile, "# test", "utf8")

  assert("clear: all three exist", existsSync(file) && existsSync(historyFile) && existsSync(handoffFile))

  // Simulate clear
  for (const f of [file, handoffFile, historyFile]) {
    try { await unlink(f) } catch {}
  }

  assert("clear: checkpoint deleted", !existsSync(file))
  assert("clear: handoff deleted", !existsSync(handoffFile))
  assert("clear: history deleted", !existsSync(historyFile))

  await rm(dir, { recursive: true, force: true })
}
await testCheckpointClearAllThreeFiles()

async function testCheckpointClearNoFiles() {
  const dir = await tmpDir()
  const file = join(dir, "checkpoint.json")
  const historyFile = join(dir, "checkpoint-history.json")
  const handoffFile = join(dir, "handoff.md")

  const results = []
  for (const f of [file, handoffFile, historyFile]) {
    try { await unlink(f); results.push("deleted") }
    catch { results.push("not found") }
  }
  assert("clear: no files ok", results.every(r => r === "not found"))

  await rm(dir, { recursive: true, force: true })
}
await testCheckpointClearNoFiles()

// ============================================================
// SUMMARY
// ============================================================
console.log(`\n${passed} passed, ${failed} failed`)
process.exit(failed ? 1 : 0)
