import { mkdir, writeFile, readFile, rm, rename } from "node:fs/promises"
import { join } from "node:path"
import { tmpdir } from "node:os"

const SCHEMA_VERSION = 2
const MAX_HISTORY = 10

const { deepMerge } = (() => {
  function deepMerge(existing, incoming) {
    return {
      version: SCHEMA_VERSION,
      updatedAt: new Date().toISOString(),
      task: {
        title: incoming?.task?.title ?? existing?.task?.title,
        objective: incoming?.task?.objective ?? existing?.task?.objective,
        status: incoming?.task?.status ?? existing?.task?.status ?? "in_progress",
      },
      summary: incoming?.summary ?? existing?.summary,
      currentPlan: incoming?.currentPlan ?? existing?.currentPlan ?? [],
      completedSteps: incoming?.completedSteps ?? existing?.completedSteps ?? [],
      nextSteps: incoming?.nextSteps ?? existing?.nextSteps ?? [],
      blockers: incoming?.blockers ?? existing?.blockers ?? [],
      filesTouched: incoming?.filesTouched ?? existing?.filesTouched ?? [],
      notes: incoming?.notes ?? existing?.notes ?? [],
    }
  }
  return { deepMerge }
})()

function sanitizeForMarkdown(s) {
  if (typeof s !== "string") return ""
  return s.replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

function sanitizeArrayForMarkdown(arr) {
  if (!arr) return []
  return arr.map((s) => sanitizeForMarkdown(s))
}

function generateHandoffMarkdown(data) {
  const title = sanitizeForMarkdown(data.task?.title ?? "Untitled Task")
  const status = sanitizeForMarkdown(data.task?.status ?? "unknown")
  const updatedAt = sanitizeForMarkdown(data.updatedAt ?? "Unknown")
  const objective = sanitizeForMarkdown(data.task?.objective ?? "Not set")
  const summary = sanitizeForMarkdown(data.summary ?? "No summary recorded.")

  const sanitizedPlan = sanitizeArrayForMarkdown(data.currentPlan)
  const sanitizedCompleted = sanitizeArrayForMarkdown(data.completedSteps)
  const sanitizedNext = sanitizeArrayForMarkdown(data.nextSteps)
  const sanitizedBlockers = sanitizeArrayForMarkdown(data.blockers)
  const sanitizedFiles = sanitizeArrayForMarkdown(data.filesTouched)
  const sanitizedNotes = sanitizeArrayForMarkdown(data.notes)

  const currentPlan =
    sanitizedPlan.length > 0
      ? sanitizedPlan.map((s, i) => `${i + 1}. ${s}`).join("\n")
      : "None recorded."

  const completedSteps =
    sanitizedCompleted.length > 0
      ? sanitizedCompleted.map((s) => `- [x] ${s}`).join("\n")
      : "None."

  const nextSteps =
    sanitizedNext.length > 0
      ? sanitizedNext.map((s) => `- [ ] ${s}`).join("\n")
      : "None."

  const blockers =
    sanitizedBlockers.length > 0
      ? sanitizedBlockers.map((b) => `- ⚠️ ${b}`).join("\n")
      : "None."

  const filesTouched =
    sanitizedFiles.length > 0
      ? sanitizedFiles.map((f) => `- 📄 ${f}`).join("\n")
      : "None recorded."

  const notes =
    sanitizedNotes.length > 0
      ? sanitizedNotes.map((n) => `- ${n}`).join("\n")
      : "None."

  return `# Handoff — ${title}

**Status:** ${status}
**Updated:** ${updatedAt}
**Objective:** ${objective}

## Summary
${summary}

## Current Plan
${currentPlan}

## Completed Steps
${completedSteps}

## Next Steps
${nextSteps}

## Blockers
${blockers}

## Files Touched
${filesTouched}

## Notes
${notes}

---
*Generated by @gitdamnit/checkpoint-orchestrator. Do not edit manually.*
*To continue: load this file and call \`checkpoint_load\` to restore full JSON state.*
`
}

let passed = 0
let failed = 0

function assert(desc, ok) {
  if (ok) { passed++; console.log(`  PASS: ${desc}`) }
  else { failed++; console.error(`  FAIL: ${desc}`) }
}

// ============================================================
// SECURITY TESTS
// ============================================================

// Security 1: Prototype pollution prevention
function testPrototypePollution() {
  const malicious = { __proto__: { polluted: true } }
  const result = deepMerge(null, malicious)
  assert("prototype pollution: polluted not set on result", !result.polluted)
  const obj = {}
  assert("prototype pollution: Object prototype not polluted", !obj.polluted)
}
testPrototypePollution()

// Security 2: Constructor poisoning
function testConstructorPoisoning() {
  const malicious = { constructor: { prototype: { polluted: true } } }
  const result = deepMerge(null, { task: malicious })
  assert("constructor poisoning: result has no task.title", result.task.title === undefined)
  const obj = {}
  assert("constructor poisoning: Object prototype not polluted", !obj.polluted)
}
testConstructorPoisoning()

// Security 3: Markdown injection in handoff — script tag
function testMarkdownInjectionScript() {
  const data = {
    version: 2,
    updatedAt: new Date().toISOString(),
    task: { title: "Test" },
    summary: '<script>alert("xss")</script>',
  }
  const md = generateHandoffMarkdown(data)
  assert("md injection: script tag escaped to &lt;", md.includes('&lt;script&gt;alert("xss")&lt;/script&gt;'))
  assert("md injection: handoff still renders", md.includes("# Handoff — Test"))
}
testMarkdownInjectionScript()

// Security 4: Markdown injection — markdown syntax abuse
function testMarkdownInjectionSyntax() {
  const data = {
    version: 2,
    updatedAt: new Date().toISOString(),
    task: { title: "Test" },
    notes: [
      "```\ncode block injection\n```",
      "![image](javascript:alert(1))",
      "[click me](data:text/html,<script>alert(1)</script>)",
    ],
  }
  const md = generateHandoffMarkdown(data)
  assert("md injection: code fence preserved", md.includes("```"))
  assert("md injection: image syntax preserved", md.includes("![image]"))
  assert("md injection: link syntax preserved", md.includes("[click me]"))
}
testMarkdownInjectionSyntax()

// Security 5: Large payload stress — massive arrays
function testLargePayload() {
  const bigArray = new Array(10000).fill("x".repeat(100))
  const result = deepMerge(null, {
    currentPlan: bigArray,
    completedSteps: bigArray,
    notes: bigArray,
  })
  assert("large payload: currentPlan has 10000 items", result.currentPlan.length === 10000)
  assert("large payload: completedSteps has 10000 items", result.completedSteps.length === 10000)
  assert("large payload: notes has 10000 items", result.notes.length === 10000)
}
testLargePayload()

// Security 6: Deeply nested string values
function testDeepNestedStrings() {
  const longString = "A".repeat(100000)
  const result = deepMerge(null, {
    summary: longString,
    task: { title: longString },
  })
  assert("deep nested: long summary preserved", result.summary.length === 100000)
  assert("deep nested: long title preserved", result.task.title.length === 100000)
}
testDeepNestedStrings()

// Security 7: Unicode boundary characters
function testUnicodeBoundary() {
  const special = {
    task: {
      title: "\u0000null byte\u0000",
      objective: "🔥".repeat(100),
      status: "in_progress",
    },
    notes: ["\uFFFFmaxunicode", "zero\u0000width"],
  }
  const result = deepMerge(null, special)
  assert("unicode: null byte preserved in title", result.task.title.includes("\u0000"))
  assert("unicode: emoji objective preserved", result.task.objective.includes("🔥"))
  assert("unicode: max unicode char preserved", result.notes[0].includes("\uFFFF"))
}
testUnicodeBoundary()

// ============================================================
// FUZZ TESTS
// ============================================================

// Fuzz 1: Non-object values for array fields
function testNonArrayFields() {
  const result = deepMerge(null, {
    currentPlan: "not an array",
    completedSteps: 123,
    blockers: null,
    filesTouched: undefined,
    notes: false,
  })
  assert("fuzz: string plan preserved as-is", result.currentPlan === "not an array")
  assert("fuzz: number steps preserved as-is", result.completedSteps === 123)
  assert("fuzz: null blockers default to array", Array.isArray(result.blockers))
  assert("fuzz: undefined defaults to array", Array.isArray(result.filesTouched))
  assert("fuzz: false notes preserved as-is", result.notes === false)
}
testNonArrayFields()

// Fuzz 2: Numeric status
function testInvalidStatus() {
  const result = deepMerge(null, { task: { status: "invalid_status_here" } })
  assert("fuzz: invalid status preserved as-is", result.task.status === "invalid_status_here")
}
testInvalidStatus()

// Fuzz 3: Non-string task title
function testNonStringTitle() {
  const result = deepMerge(null, { task: { title: 12345 } })
  assert("fuzz: numeric title preserved", result.task.title === 12345)
}
testNonStringTitle()

// Fuzz 4: Empty object deepMerge
function testEmptyObjectMerge() {
  const existing = {
    version: 2,
    updatedAt: new Date().toISOString(),
    task: { title: "Existing", status: "in_progress" },
    currentPlan: ["Step 1"],
    completedSteps: [],
  }
  const result = deepMerge(existing, {})
  assert("fuzz: empty merge keeps title", result.task.title === "Existing")
  assert("fuzz: empty merge keeps status", result.task.status === "in_progress")
  assert("fuzz: empty merge keeps plan", result.currentPlan[0] === "Step 1")
}
testEmptyObjectMerge()

// Fuzz 5: undefined incoming
function testUndefinedIncoming() {
  const result = deepMerge(null, undefined)
  assert("fuzz: undefined incoming handled", result !== null && result !== undefined)
  assert("fuzz: undefined incoming has version", result.version === 2)
}
testUndefinedIncoming()

// Fuzz 6: null incoming task
function testNullTaskField() {
  const result = deepMerge(null, { task: null })
  assert("fuzz: null task handled", result.task !== null && result.task !== undefined)
  assert("fuzz: null task defaults title undefined", result.task.title === undefined)
}
testNullTaskField()

// Fuzz 7: Extra unknown fields
function testExtraFields() {
  const result = deepMerge(null, { task: { title: "Test" }, unknownField: "should be dropped", another: { nested: true } })
  assert("fuzz: unknown fields don't cause error", result.task.title === "Test")
  assert("fuzz: unknown fields not in result", !result.unknownField)
}
testExtraFields()

// ============================================================
// ATOMIC INTEGRITY TESTS
// ============================================================

// Integrity 1: Atomic write with temp + rename
async function testAtomicWriteIntegrity() {
  const dir = join(tmpdir(), "cp-atomic-" + Date.now())
  await mkdir(dir, { recursive: true })
  const file = join(dir, "checkpoint.json")

  const data = { version: 2, updatedAt: new Date().toISOString(), task: { title: "atomic test" } }
  const tmp = file + ".tmp." + Date.now()
  await writeFile(tmp, JSON.stringify(data))
  await rename(tmp, file)

  const loaded = JSON.parse(await readFile(file, "utf8"))
  assert("integrity: atomic write valid", loaded.task.title === "atomic test")

  // Temp file should NOT exist
  let tempExists = false
  try { await readFile(tmp); tempExists = true } catch {}
  assert("integrity: temp file cleaned", !tempExists)

  await rm(dir, { recursive: true, force: true })
}
await testAtomicWriteIntegrity()

// Integrity 2: Partial write (simulated crash) doesn't corrupt
async function testPartialWriteSafety() {
  const dir = join(tmpdir(), "cp-partial-" + Date.now())
  await mkdir(dir, { recursive: true })
  const file = join(dir, "checkpoint.json")

  // Write valid data first
  await writeFile(file, JSON.stringify({ version: 2, updatedAt: new Date().toISOString(), task: { title: "original" } }))

  // Simulate crash mid-write by writing partial content directly (bypassing atomic)
  await writeFile(file, '{"version": 2, "updatedAt": "2026-01-01", ')

  // Read should succeed (or return null) but not crash
  let loaded = null
  try { loaded = JSON.parse(await readFile(file, "utf8")) } catch {}
  assert("integrity: partial write returns null", loaded === null)

  // Clean temp files if any
  await rm(dir, { recursive: true, force: true })
}
await testPartialWriteSafety()

// Integrity 3: Temp file collision on rapid saves
async function testTempFileUniqueness() {
  const dir = join(tmpdir(), "cp-rapid-" + Date.now())
  await mkdir(dir, { recursive: true })
  const file = join(dir, "checkpoint.json")

  const saves = []
  for (let i = 0; i < 20; i++) {
    const tmp = file + ".tmp." + Date.now()
    saves.push(tmp)
    await writeFile(tmp, JSON.stringify({ version: 2, updatedAt: new Date().toISOString(), task: { title: `save-${i}` } }))
    await rename(tmp, file).catch(() => {})
  }

  const loaded = JSON.parse(await readFile(file, "utf8"))
  assert("integrity: rapid saves produce valid file", loaded.version === 2)
  assert("integrity: last save wins", loaded.task.title.startsWith("save-"))

  // All temp files should be cleaned
  for (const tmp of saves) {
    let exists = true
    try { await readFile(tmp) } catch { exists = false }
    if (exists) {
      assert(`integrity: temp file ${tmp} should be gone`, false)
    }
  }

  await rm(dir, { recursive: true, force: true })
}
await testTempFileUniqueness()

// ============================================================
// STRESS TESTS
// ============================================================

// Stress 1: Rapid sequential deepMerge calls
function testRapidMerge() {
  let state = null
  for (let i = 0; i < 100; i++) {
    state = deepMerge(state, {
      task: { title: `iteration-${i}`, status: i % 2 === 0 ? "in_progress" : "blocked" },
      completedSteps: [`step-${i}`],
      notes: [`note-${i}`],
    })
  }
  assert("stress: 100 merges final title correct", state.task.title === "iteration-99")
  assert("stress: 100 merges last completedStep correct", state.completedSteps[0] === "step-99")
  assert("stress: 100 merges last note correct", state.notes[0] === "note-99")
}
testRapidMerge()

// Stress 2: History ring buffer at limit
function testHistoryRingBufferLimit() {
  const snapshots = []
  for (let i = 1; i <= MAX_HISTORY + 1; i++) {
    snapshots.push({ name: `snap-${i}`, savedAt: new Date().toISOString(), data: { version: 2 } })
  }
  const pruned = snapshots.slice(-MAX_HISTORY)
  assert("stress: ring buffer at limit +1", pruned.length === MAX_HISTORY)
  assert("stress: oldest dropped (snap-2 is oldest)", pruned[0].name === "snap-2")
  assert("stress: newest kept (snap-11)", pruned[pruned.length - 1].name === `snap-${MAX_HISTORY + 1}`)
}
testHistoryRingBufferLimit()

// Stress 3: Zero-length arrays
function testZeroLengthArrays() {
  const result = deepMerge(null, {
    currentPlan: [],
    completedSteps: [],
    blockers: [],
    filesTouched: [],
    notes: [],
  })
  assert("stress: empty arrays handled", Array.isArray(result.currentPlan))
  assert("stress: empty arrays length 0", result.currentPlan.length === 0)
}
testZeroLengthArrays()

// Stress 4: All fields at once with max data
function testAllFieldsMax() {
  const now = new Date().toISOString()
  const big = "x".repeat(5000)
  const arr = new Array(100).fill(big)
  const result = deepMerge(null, {
    task: { title: big, objective: big, status: "in_progress" },
    summary: big,
    currentPlan: arr,
    completedSteps: arr,
    nextSteps: arr,
    blockers: arr,
    filesTouched: arr,
    notes: arr,
  })
  assert("stress: all fields max — title", result.task.title.length === 5000)
  assert("stress: all fields max — plan count", result.currentPlan.length === 100)
  assert("stress: all fields max — note count", result.notes.length === 100)
}
testAllFieldsMax()

// ============================================================
// EDGE CASE TESTS
// ============================================================

// Edge 1: Double merge same data
function testDoubleMergeSame() {
  const input = { task: { title: "Same", status: "in_progress" } }
  const first = deepMerge(null, input)
  const second = deepMerge(first, input)
  assert("edge: double merge same title", second.task.title === "Same")
  assert("edge: double merge same status", second.task.status === "in_progress")
}
testDoubleMergeSame()

// Edge 2: Status transitions — all valid states
function testAllStatusTransitions() {
  const states = ["not_started", "in_progress", "blocked", "done"]
  let state = null
  for (const s of states) {
    state = deepMerge(state, { task: { status: s } })
    assert(`edge: status transition to ${s}`, state.task.status === s)
  }
}
testAllStatusTransitions()

// Edge 3: Null existing, null incoming
function testDoubleNull() {
  const result = deepMerge(null, null)
  assert("edge: double null result created", result !== null)
  assert("edge: double null has version", result.version === 2)
}
testDoubleNull()

// Edge 4: Existing but no incoming task
function testNoIncomingTask() {
  const existing = {
    version: 2,
    updatedAt: new Date().toISOString(),
    task: { title: "Keep me" },
  }
  const result = deepMerge(existing, {})
  assert("edge: no incoming task keeps existing title", result.task.title === "Keep me")
}
testNoIncomingTask()

// Edge 5: Handoff markdown with all fields empty — verify complete output
function testHandoffAllEmpty() {
  const data = { version: 2, updatedAt: new Date().toISOString(), task: {} }
  const md = generateHandoffMarkdown(data)
  assert("edge: all empty handoff starts with H1", md.startsWith("# Handoff"))
  assert("edge: all empty has footer", md.includes("Generated by @gitdamnit/checkpoint-orchestrator"))
  const lines = md.split("\n").filter(l => l.trim())
  assert("edge: all empty handoff has content", lines.length > 5)
}
testHandoffAllEmpty()

// Edge 6: Handoff markdown with special chars in fields
function testHandoffSpecialChars() {
  const data = {
    version: 2,
    updatedAt: new Date().toISOString(),
    task: { title: "Title with [brackets] and (parens)", status: "in_progress" },
    notes: ["Line 1\nLine 2", "Tab\tseparated", "Carriage\rreturn"],
  }
  const md = generateHandoffMarkdown(data)
  assert("edge: special chars brackets", md.includes("[brackets]"))
  assert("edge: special chars parens", md.includes("(parens)"))
  assert("edge: multiline note keeps newline", md.includes("Line 1\n"))
}
testHandoffSpecialChars()

// Edge 7: Schema version boundary
function testVersionBoundary() {
  const v1 = { version: 1 }
  const v2 = { version: 2 }
  assert("edge: v1 < v2", v1.version < v2.version)
  assert("edge: v2 not < v2", !(v2.version < v2.version))
  assert("edge: no version treated as < 2", (undefined < 2) === false)
}
testVersionBoundary()

// Edge 8: Filesystem — permission denied (simulated)
async function testMissingDirectory() {
  const dir = join(tmpdir(), "cp-missing-" + Date.now())
  const file = join(dir, "checkpoint.json")

  // Directory doesn't exist — write should fail
  let threw = false
  try {
    await writeFile(file, JSON.stringify({ version: 2, updatedAt: new Date().toISOString(), task: { title: "test" } }))
  } catch {
    threw = true
  }
  assert("edge: write to non-existent dir fails", threw)

  // Create dir first, then succeed
  await mkdir(dir, { recursive: true })
  await writeFile(file, JSON.stringify({ version: 2, updatedAt: new Date().toISOString(), task: { title: "test" } }))
  const loaded = JSON.parse(await readFile(file, "utf8"))
  assert("edge: write succeeds after mkdir", loaded.task.title === "test")

  await rm(dir, { recursive: true, force: true })
}
await testMissingDirectory()

// Edge 9: Concurrent read/write simulation
function testTOCTOUPattern() {
  const original = { name: "target", savedAt: new Date().toISOString(), data: { version: 2, updatedAt: new Date().toISOString(), task: { title: "target" } } }
  const newEntry = { name: "new", savedAt: new Date().toISOString(), data: { version: 2, updatedAt: new Date().toISOString(), task: { title: "new" } } }

  // Simulate the bug: load history, another write happens, load history again
  let history = { snapshots: [original] }
  const preRestore = [...history.snapshots]
  // Simulate concurrent write
  history.snapshots.push(newEntry)
  // Now re-read (second load) — we got a different snapshot set
  const targetFromSecondRead = history.snapshots.find(s => s.name === "target")
  assert("edge: TOCTOU — target still findable", targetFromSecondRead.name === "target")
  assert("edge: TOCTOU — history has extra entry", history.snapshots.length === 2)
}
testTOCTOUPattern()

// Edge 10: Verify handoff.md emoji rendering doesn't break on long strings
function testHandoffEmojiLongStrings() {
  const longBlocker = "Waiting on " + "very ".repeat(100) + "long dependency chain"
  const data = {
    version: 2,
    updatedAt: new Date().toISOString(),
    task: { title: "Test" },
    blockers: [longBlocker],
  }
  const md = generateHandoffMarkdown(data)
  assert("edge: long blocker preserved", md.includes("very ".repeat(100)))
  assert("edge: long blocker emoji prefix", md.includes("⚠️"))
}
testHandoffEmojiLongStrings()

// Edge 11: Null-ish values in all positions
function testNullishAllPositions() {
  const result = deepMerge(null, {
    task: null,
    summary: null,
    currentPlan: null,
    completedSteps: null,
    nextSteps: null,
    blockers: null,
    filesTouched: null,
    notes: null,
  })
  assert("edge: nullish all — version exists", result.version === 2)
  assert("edge: nullish all — task is object", typeof result.task === "object")
  assert("edge: nullish all — all arrays empty", result.currentPlan.length === 0)
}
testNullishAllPositions()

// Edge 12: Empty status (should default to in_progress)
function testDefaultStatus() {
  const result = deepMerge(null, { task: { title: "No status" } })
  assert("edge: no status defaults to in_progress", result.task.status === "in_progress")
}
testDefaultStatus()

// ============================================================
// SUMMARY
// ============================================================
console.log(`\n${passed} passed, ${failed} failed`)
process.exit(failed ? 1 : 0)
