import { mkdir, writeFile, readFile, rm } from "node:fs/promises"
import { join } from "node:path"
import { tmpdir } from "node:os"

const SCHEMA_VERSION = 2
const MAX_HISTORY = 10
const AUTOSAVE_EVERY_N_MESSAGES = 5

const { deepMerge } = (() => {
  function deepMerge(existing, incoming) {
    return {
      version: SCHEMA_VERSION,
      updatedAt: new Date().toISOString(),
      task: {
        title: incoming.task?.title ?? existing?.task?.title,
        objective: incoming.task?.objective ?? existing?.task?.objective,
        status: incoming.task?.status ?? existing?.task?.status ?? "in_progress",
      },
      summary: incoming.summary ?? existing?.summary,
      currentPlan: incoming.currentPlan ?? existing?.currentPlan ?? [],
      completedSteps: incoming.completedSteps ?? existing?.completedSteps ?? [],
      nextSteps: incoming.nextSteps ?? existing?.nextSteps ?? [],
      blockers: incoming.blockers ?? existing?.blockers ?? [],
      filesTouched: incoming.filesTouched ?? existing?.filesTouched ?? [],
      notes: incoming.notes ?? existing?.notes ?? [],
    }
  }
  return { deepMerge }
})()

function generateHandoffMarkdown(data) {
  const title = data.task?.title ?? "Untitled Task"
  const status = data.task?.status ?? "unknown"
  const updatedAt = data.updatedAt ?? "Unknown"
  const objective = data.task?.objective ?? "Not set"
  const summary = data.summary ?? "No summary recorded."

  const currentPlan =
    data.currentPlan && data.currentPlan.length > 0
      ? data.currentPlan.map((s, i) => `${i + 1}. ${s}`).join("\n")
      : "None recorded."

  const completedSteps =
    data.completedSteps && data.completedSteps.length > 0
      ? data.completedSteps.map((s) => `- [x] ${s}`).join("\n")
      : "None."

  const nextSteps =
    data.nextSteps && data.nextSteps.length > 0
      ? data.nextSteps.map((s) => `- [ ] ${s}`).join("\n")
      : "None."

  const blockers =
    data.blockers && data.blockers.length > 0
      ? data.blockers.map((b) => `- ⚠️ ${b}`).join("\n")
      : "None."

  const filesTouched =
    data.filesTouched && data.filesTouched.length > 0
      ? data.filesTouched.map((f) => `- 📄 ${f}`).join("\n")
      : "None recorded."

  const notes =
    data.notes && data.notes.length > 0
      ? data.notes.map((n) => `- ${n}`).join("\n")
      : "None."

  return `# Handoff — ${title}

**Status:** ${status}
**Updated:** ${updatedAt}
**Objective:** ${objective}

## Summary
${summary}

## Current Plan
${currentPlan}

## Completed Steps
${completedSteps}

## Next Steps
${nextSteps}

## Blockers
${blockers}

## Files Touched
${filesTouched}

## Notes
${notes}

---
*Generated by @gitdamnit/checkpoint-orchestrator. Do not edit manually.*
*To continue: load this file and call \`checkpoint_load\` to restore full JSON state.*
`
}

let passed = 0
let failed = 0

function assert(desc, ok) {
  if (ok) { passed++; console.log(`  PASS: ${desc}`) }
  else { failed++; console.error(`  FAIL: ${desc}`) }
}

// Test 1: Fresh save
const first = deepMerge(null, {
  task: { title: "Fix auth", status: "in_progress" },
  currentPlan: ["Investigate", "Implement"],
  filesTouched: ["src/auth.ts"],
})
assert("fresh save sets title", first.task.title === "Fix auth")
assert("fresh save sets status", first.task.status === "in_progress")
assert("fresh save arrays default to empty", Array.isArray(first.completedSteps))
assert("fresh save has version 2", first.version === 2)

// Test 2: Deep merge preserves existing task fields
const second = deepMerge(first, {
  task: { status: "blocked" },
  blockers: ["Waiting on API key"],
})
assert("deep merge keeps title from first save", second.task.title === "Fix auth")
assert("deep merge updates status", second.task.status === "blocked")
assert("deep merge keeps plan from first save", second.currentPlan[0] === "Investigate")

// Test 3: Partial update doesn't clobber arrays
const third = deepMerge(second, {
  completedSteps: ["Investigate"],
  nextSteps: ["Get API key", "Implement"],
})
assert("partial update adds completedSteps", third.completedSteps[0] === "Investigate")
assert("partial merge keeps blockers", third.blockers[0] === "Waiting on API key")
assert("partial merge keeps plan", third.currentPlan[0] === "Investigate")

// Test 4: Status progression
const fourth = deepMerge(third, {
  task: { status: "done" },
  summary: "Auth fix complete",
})
assert("status progression", fourth.task.status === "done")
assert("summary set", fourth.summary === "Auth fix complete")

// Test 5: Atomic write test using temp file + rename
async function testAtomicWrite() {
  const dir = join(tmpdir(), "cp-test-" + Date.now())
  await mkdir(dir, { recursive: true })
  const file = join(dir, "checkpoint.json")
  const data = { version: 2, updatedAt: new Date().toISOString(), task: { title: "test" } }

  // Write atomically
  const tmp = file + ".tmp." + Date.now()
  await writeFile(tmp, JSON.stringify(data))
  await import("node:fs/promises").then(m => m.rename(tmp, file))

  const loaded = JSON.parse(await readFile(file, "utf8"))
  assert("atomic write produces valid file", loaded.task.title === "test")
  assert("temp file cleaned up after rename", !await import("node:fs").then(m => m.existsSync(tmp)))

  await rm(dir, { recursive: true, force: true })
}

await testAtomicWrite()

// Test 6: Handoff.md generation shape
async function testHandoffGeneration() {
  const dir = join(tmpdir(), "cp-handoff-test-" + Date.now())
  await mkdir(dir, { recursive: true })

  const data = {
    version: 2,
    updatedAt: "2026-01-01T00:00:00.000Z",
    task: { title: "Test Task", status: "in_progress", objective: "Do the thing" },
    summary: "Making progress",
    currentPlan: ["Step A", "Step B"],
    completedSteps: ["Step A"],
    nextSteps: ["Step B"],
    blockers: ["Waiting on CI"],
    filesTouched: ["src/index.ts"],
    notes: ["Remember to update CHANGELOG"],
  }

  assert("handoff data has title", data.task.title === "Test Task")
  assert("handoff nextSteps is array", Array.isArray(data.nextSteps))
  assert("handoff blockers is array", Array.isArray(data.blockers))
  assert("handoff version is 2", data.version === 2)

  await rm(dir, { recursive: true, force: true })
}
await testHandoffGeneration()

// Test 7: Ring buffer pruning
function testRingBufferPruning() {
  const snapshots = []
  for (let i = 1; i <= 12; i++) {
    snapshots.push({ name: `snap-${i}`, savedAt: new Date().toISOString(), data: { version: 2 } })
  }
  const pruned = snapshots.slice(-MAX_HISTORY)

  assert("ring buffer prunes to MAX_HISTORY", pruned.length === MAX_HISTORY)
  assert("ring buffer keeps newest entries", pruned[pruned.length - 1].name === "snap-12")
  assert("ring buffer drops oldest entries", pruned[0].name === "snap-3")
}
testRingBufferPruning()

// Test 8: Snapshot history shape
function testSnapshotHistoryShape() {
  const snapshot = {
    name: "before-refactor",
    savedAt: new Date().toISOString(),
    data: {
      version: 2,
      updatedAt: new Date().toISOString(),
      task: { title: "Refactor auth", status: "in_progress" },
      completedSteps: ["Setup"],
      nextSteps: ["Implement"],
      blockers: [],
      filesTouched: [],
      notes: [],
      currentPlan: [],
    },
  }
  assert("snapshot has name", typeof snapshot.name === "string")
  assert("snapshot has savedAt", typeof snapshot.savedAt === "string")
  assert("snapshot.data has version", snapshot.data.version === 2)
  assert("snapshot.data task has title", snapshot.data.task.title === "Refactor auth")
}
testSnapshotHistoryShape()

// Test 9: Auto-generated snapshot name format
function testAutoSnapshotName() {
  const ts = Date.now()
  const autoName = `auto-${ts}`
  assert("auto snapshot name starts with auto-", autoName.startsWith("auto-"))
  assert("auto snapshot name has numeric suffix", !isNaN(Number(autoName.split("auto-")[1])))

  const restoreName = `pre-restore-${ts}`
  assert("pre-restore name starts correctly", restoreName.startsWith("pre-restore-"))
}
testAutoSnapshotName()

// Test 10: Schema version mismatch detection
function testVersionMismatch() {
  const oldData = { version: 1, updatedAt: "2025-01-01T00:00:00.000Z", task: { title: "Old task" } }
  assert("version mismatch is detectable", oldData.version < SCHEMA_VERSION)
  assert("old data still has title accessible", oldData.task.title === "Old task")
}
testVersionMismatch()

// Test 11: Chat.message counter reset logic
function testMessageCounterReset() {
  let counter = 0

  // Simulate 5 messages
  for (let i = 0; i < 5; i++) counter++
  assert("counter reaches threshold", counter >= AUTOSAVE_EVERY_N_MESSAGES)

  // Simulate reset after save
  counter = 0
  assert("counter resets to 0 after save", counter === 0)

  // Simulate manual save resets counter mid-count
  counter = 3
  counter = 0
  assert("manual save resets counter", counter === 0)
}
testMessageCounterReset()

// Test 12: Deep merge with schema v2
function testDeepMergeWithSchemaV2() {
  const result = deepMerge(null, { task: { title: "v2 test" } })
  assert("deepMerge uses SCHEMA_VERSION 2", result.version === 2)

  const merged = deepMerge(result, { task: { status: "done" } })
  assert("merged version stays at 2", merged.version === 2)
  assert("merged preserves title", merged.task.title === "v2 test")
  assert("merged updates status", merged.task.status === "done")
}
testDeepMergeWithSchemaV2()

// Test 13: Handoff markdown rendering
function testHandoffMarkdownRendering() {
  const data = {
    version: 2,
    updatedAt: "2026-01-01T00:00:00.000Z",
    task: { title: "Render Test", status: "in_progress", objective: "Test rendering" },
    summary: "Testing handoff generation",
    currentPlan: ["Plan A", "Plan B"],
    completedSteps: ["Done 1"],
    nextSteps: ["Next 1", "Next 2"],
    blockers: ["Blocked by X"],
    filesTouched: ["a.ts", "b.ts"],
    notes: ["Note 1"],
  }
  const md = generateHandoffMarkdown(data)

  assert("handoff contains title header", md.includes("# Handoff — Render Test"))
  assert("handoff contains status", md.includes("**Status:** in_progress"))
  assert("handoff contains objective", md.includes("**Objective:** Test rendering"))
  assert("handoff contains summary", md.includes("Testing handoff generation"))
  assert("handoff contains numbered plan", md.includes("1. Plan A"))
  assert("handoff contains checked step", md.includes("- [x] Done 1"))
  assert("handoff contains unchecked steps", md.includes("- [ ] Next 1"))
  assert("handoff contains blocker prefix", md.includes("⚠️ Blocked by X"))
  assert("handoff contains file prefix", md.includes("📄 a.ts"))
  assert("handoff contains footer", md.includes("Generated by @gitdamnit/checkpoint-orchestrator"))
}
testHandoffMarkdownRendering()

// Test 14: Empty fields fallback rendering
function testEmptyFieldsFallback() {
  const data = {
    version: 2,
    updatedAt: "2026-01-01T00:00:00.000Z",
    task: {},
  }
  const md = generateHandoffMarkdown(data)

  assert("empty title falls back to Untitled", md.includes("# Handoff — Untitled Task"))
  assert("empty status falls back to unknown", md.includes("**Status:** unknown"))
  assert("empty objective falls back to Not set", md.includes("**Objective:** Not set"))
  assert("empty summary falls back", md.includes("No summary recorded."))
  assert("empty plan falls back", md.includes("None recorded."))
  assert("empty completedSteps falls back", md.includes("None."))
  assert("empty nextSteps falls back", md.includes("None."))
  assert("empty blockers falls back", md.includes("None."))
  assert("empty filesTouched falls back", md.includes("None recorded."))
  assert("empty notes falls back", md.includes("None."))
}
testEmptyFieldsFallback()

// Test 15: History pruning edge cases
function testHistoryPruningEdgeCases() {
  // Exactly 10 entries — no pruning
  const exactly10 = []
  for (let i = 1; i <= 10; i++) {
    exactly10.push({ name: `e-${i}` })
  }
  const pruned10 = exactly10.slice(-MAX_HISTORY)
  assert("10 entries stays at 10", pruned10.length === 10)
  assert("10 entries keeps first", pruned10[0].name === "e-1")

  // 11 entries — prunes 1
  const eleven = []
  for (let i = 1; i <= 11; i++) {
    eleven.push({ name: `el-${i}` })
  }
  const pruned11 = eleven.slice(-MAX_HISTORY)
  assert("11 entries prunes to 10", pruned11.length === 10)
  assert("11 entries drops e-1", pruned11[0].name === "el-2")

  // 20 entries — prunes 10
  const twenty = []
  for (let i = 1; i <= 20; i++) {
    twenty.push({ name: `t-${i}` })
  }
  const pruned20 = twenty.slice(-MAX_HISTORY)
  assert("20 entries prunes to 10", pruned20.length === 10)
  assert("20 entries keeps t-11 as oldest", pruned20[0].name === "t-11")
  assert("20 entries keeps t-20 as newest", pruned20[9].name === "t-20")
}
testHistoryPruningEdgeCases()

// Test 16: Restore undo point naming
function testRestoreUndoPointNaming() {
  const ts = Date.now()
  const undoName = `pre-restore-${ts}`

  assert("undo name starts with pre-restore-", undoName.startsWith("pre-restore-"))
  const suffix = undoName.split("pre-restore-")[1]
  assert("undo name has numeric timestamp", !isNaN(Number(suffix)))
  assert("undo timestamp matches original", Number(suffix) === ts)
}
testRestoreUndoPointNaming()

// Test 17: Snapshot entry structure validation
function testSnapshotEntryStructure() {
  const entry = {
    name: "test-snapshot",
    savedAt: "2026-01-01T00:00:00.000Z",
    data: {
      version: 2,
      updatedAt: "2026-01-01T00:00:00.000Z",
      task: { title: "Test", status: "in_progress" },
      summary: "Test summary",
      currentPlan: ["A"],
      completedSteps: [],
      nextSteps: ["B"],
      blockers: [],
      filesTouched: [],
      notes: [],
    },
  }

  assert("entry has string name", typeof entry.name === "string")
  assert("entry has string savedAt", typeof entry.savedAt === "string")
  assert("entry.data is object", typeof entry.data === "object")
  assert("entry.data.version is 2", entry.data.version === 2)
  assert("entry.data has task", entry.data.task !== undefined)
  assert("entry.data has summary", entry.data.summary !== undefined)
  assert("entry.data has arrays", Array.isArray(entry.data.currentPlan))
}
testSnapshotEntryStructure()

// Test 18: History reverse ordering for checkpoint_list
function testHistoryReverseOrdering() {
  const snapshots = []
  for (let i = 1; i <= 5; i++) {
    snapshots.push({ name: `snap-${i}`, savedAt: `2026-01-0${i}T00:00:00.000Z`, data: { task: { title: `Task ${i}` } } })
  }
  const reversed = [...snapshots].reverse()

  assert("reversed newest first", reversed[0].name === "snap-5")
  assert("reversed last is oldest", reversed[4].name === "snap-1")
  assert("reversed preserves all entries", reversed.length === 5)
}
testHistoryReverseOrdering()

// Test 19: Deep copy isolation for snapshot data
function testSnapshotDataDeepCopy() {
  const original = {
    version: 2,
    updatedAt: "2026-01-01T00:00:00.000Z",
    task: { title: "Original", status: "in_progress" },
    completedSteps: ["Step 1"],
  }
  const copy = JSON.parse(JSON.stringify(original))

  copy.task.title = "Modified"
  copy.completedSteps.push("Step 2")

  assert("original title unchanged", original.task.title === "Original")
  assert("original steps unchanged", original.completedSteps.length === 1)
  assert("copy has modified title", copy.task.title === "Modified")
  assert("copy has extra step", copy.completedSteps.length === 2)
}
testSnapshotDataDeepCopy()

// Test 20: Message counter boundary conditions
function testMessageCounterBoundaryConditions() {
  let counter = 0

  // 4 messages — should NOT trigger
  for (let i = 0; i < 4; i++) counter++
  assert("4 messages below threshold", counter < AUTOSAVE_EVERY_N_MESSAGES)

  // 5th message — should trigger
  counter++
  assert("5 messages hits threshold", counter >= AUTOSAVE_EVERY_N_MESSAGES)

  // Reset and verify
  counter = 0
  assert("reset works", counter === 0)

  // 6 messages — should still trigger at 5
  for (let i = 0; i < 6; i++) counter++
  assert("6 messages exceeds threshold", counter >= AUTOSAVE_EVERY_N_MESSAGES)
}
testMessageCounterBoundaryConditions()

console.log(`\n${passed} passed, ${failed} failed`)
process.exit(failed ? 1 : 0)
