import { mkdir, readFile, writeFile, rename, unlink } from "node:fs/promises"
import { join } from "node:path"
import type { Plugin } from "@opencode-ai/plugin"
import { tool } from "@opencode-ai/plugin"

// Schema version — increment when CheckpointData shape changes in a breaking way
const SCHEMA_VERSION = 2
const MAX_HISTORY = 10
const HISTORY_FILE_NAME = "checkpoint-history.json"
const AUTOSAVE_EVERY_N_MESSAGES = 5
const CHECKPOINT_DIR = ".opencode/state"
const FILE_NAME = "checkpoint.json"
const HANDOFF_FILE_NAME = "handoff.md"

type CheckpointData = {
  version: number
  updatedAt: string
  task?: {
    title?: string
    objective?: string
    status?: "not_started" | "in_progress" | "blocked" | "done"
  }
  summary?: string
  currentPlan?: string[]
  completedSteps?: string[]
  nextSteps?: string[]
  blockers?: string[]
  filesTouched?: string[]
  notes?: string[]
}

type SnapshotEntry = {
  name: string
  savedAt: string
  data: CheckpointData
}

type HistoryData = {
  snapshots: SnapshotEntry[]
}

function generateHandoffMarkdown(data: CheckpointData): string {
  const title = data.task?.title ?? "Untitled Task"
  const status = data.task?.status ?? "unknown"
  const updatedAt = data.updatedAt ?? "Unknown"
  const objective = data.task?.objective ?? "Not set"
  const summary = data.summary ?? "No summary recorded."

  const currentPlan =
    data.currentPlan && data.currentPlan.length > 0
      ? data.currentPlan.map((s, i) => `${i + 1}. ${s}`).join("\n")
      : "None recorded."

  const completedSteps =
    data.completedSteps && data.completedSteps.length > 0
      ? data.completedSteps.map((s) => `- [x] ${s}`).join("\n")
      : "None."

  const nextSteps =
    data.nextSteps && data.nextSteps.length > 0
      ? data.nextSteps.map((s) => `- [ ] ${s}`).join("\n")
      : "None."

  const blockers =
    data.blockers && data.blockers.length > 0
      ? data.blockers.map((b) => `- ⚠️ ${b}`).join("\n")
      : "None."

  const filesTouched =
    data.filesTouched && data.filesTouched.length > 0
      ? data.filesTouched.map((f) => `- 📄 ${f}`).join("\n")
      : "None recorded."

  const notes =
    data.notes && data.notes.length > 0
      ? data.notes.map((n) => `- ${n}`).join("\n")
      : "None."

  return `# Handoff — ${title}

**Status:** ${status}
**Updated:** ${updatedAt}
**Objective:** ${objective}

## Summary
${summary}

## Current Plan
${currentPlan}

## Completed Steps
${completedSteps}

## Next Steps
${nextSteps}

## Blockers
${blockers}

## Files Touched
${filesTouched}

## Notes
${notes}

---
*Generated by @gitdamnit/checkpoint-orchestrator. Do not edit manually.*
*To continue: load this file and call \`checkpoint_load\` to restore full JSON state.*
`
}

async function ensureDir(path: string): Promise<void> {
  await mkdir(path, { recursive: true })
}

async function readJSON<T>(path: string): Promise<T | null> {
  try {
    return JSON.parse(await readFile(path, "utf8")) as T
  } catch {
    return null
  }
}

function deepMerge(
  existing: CheckpointData | null,
  incoming: Partial<CheckpointData>,
): CheckpointData {
  return {
    version: SCHEMA_VERSION,
    updatedAt: new Date().toISOString(),
    task: {
      title: incoming.task?.title ?? existing?.task?.title,
      objective: incoming.task?.objective ?? existing?.task?.objective,
      status: incoming.task?.status ?? existing?.task?.status ?? "in_progress",
    },
    summary: incoming.summary ?? existing?.summary,
    currentPlan: incoming.currentPlan ?? existing?.currentPlan ?? [],
    completedSteps: incoming.completedSteps ?? existing?.completedSteps ?? [],
    nextSteps: incoming.nextSteps ?? existing?.nextSteps ?? [],
    blockers: incoming.blockers ?? existing?.blockers ?? [],
    filesTouched: incoming.filesTouched ?? existing?.filesTouched ?? [],
    notes: incoming.notes ?? existing?.notes ?? [],
  }
}

export const CheckpointPlugin: Plugin = async (ctx) => {
  const dir = join(ctx.directory, CHECKPOINT_DIR)
  const file = join(dir, FILE_NAME)
  const historyFile = join(dir, HISTORY_FILE_NAME)
  const handoffFile = join(dir, HANDOFF_FILE_NAME)

  let lastInjectedHash = ""
  let messagesSinceLastSave = 0
  let isDirty = false

  async function load(): Promise<CheckpointData | null> {
    const loaded = await readJSON<CheckpointData>(file)
    if (loaded && loaded.version && loaded.version < SCHEMA_VERSION) {
      await ctx.client.app.log({
        body: {
          service: "checkpoint",
          level: "warn",
          message: `Checkpoint schema version mismatch: file is v${loaded.version}, plugin expects v${SCHEMA_VERSION}. Data loaded as-is — consider running checkpoint_clear and starting fresh.`,
          extra: { fileVersion: loaded.version, pluginVersion: SCHEMA_VERSION },
        },
      })
    }
    return loaded
  }

  async function loadHistory(): Promise<HistoryData> {
    const existing = await readJSON<HistoryData>(historyFile)
    return existing ?? { snapshots: [] }
  }

  async function saveHistory(history: HistoryData): Promise<void> {
    const tmp = historyFile + ".tmp." + Date.now()
    await writeFile(tmp, JSON.stringify(history, null, 2), "utf8")
    await rename(tmp, historyFile)
  }

  async function save(
    data: Partial<CheckpointData>,
    snapshotName?: string,
  ): Promise<CheckpointData> {
    await ensureDir(dir)

    const existing = await load()
    const merged = deepMerge(existing, data)

    const tmp = file + ".tmp." + Date.now()
    await writeFile(tmp, JSON.stringify(merged, null, 2), "utf8")
    await rename(tmp, file)

    const handoff = generateHandoffMarkdown(merged)
    await writeFile(handoffFile, handoff, "utf8")

    const name = snapshotName ?? `auto-${Date.now()}`
    const savedAt = new Date().toISOString()
    const snapshot: SnapshotEntry = {
      name,
      savedAt,
      data: JSON.parse(JSON.stringify(merged)),
    }

    const history = await loadHistory()
    history.snapshots.push(snapshot)
    if (history.snapshots.length > MAX_HISTORY) {
      history.snapshots = history.snapshots.slice(-MAX_HISTORY)
    }
    await saveHistory(history)

    await ctx.client.app.log({
      body: {
        service: "checkpoint",
        level: "info",
        message: "Checkpoint saved",
        extra: { file, updatedAt: merged.updatedAt },
      },
    })

    return merged
  }

  return {
    tool: {
      checkpoint_save: tool({
        description:
          "Save or update persistent task state for later recovery or handoff. Fields are deep-merged so partial updates don't clobber existing data. Optionally provide snapshotName to tag this save for later reference.",
        args: {
          title: tool.schema.string().optional(),
          objective: tool.schema.string().optional(),
          status: tool.schema
            .enum(["not_started", "in_progress", "blocked", "done"])
            .optional(),
          summary: tool.schema.string().optional(),
          currentPlan: tool.schema.array(tool.schema.string()).optional(),
          completedSteps: tool.schema.array(tool.schema.string()).optional(),
          nextSteps: tool.schema.array(tool.schema.string()).optional(),
          blockers: tool.schema.array(tool.schema.string()).optional(),
          filesTouched: tool.schema.array(tool.schema.string()).optional(),
          notes: tool.schema.array(tool.schema.string()).optional(),
          snapshotName: tool.schema.string().optional(),
        },
        async execute(args) {
          // Trigger C: explicit agent-initiated save
          // This is the primary save path. Triggers A and B are safety nets only.
          const result = await save(
            {
              task: {
                title: args.title,
                objective: args.objective,
                status: args.status,
              },
              summary: args.summary,
              currentPlan: args.currentPlan,
              completedSteps: args.completedSteps,
              nextSteps: args.nextSteps,
              blockers: args.blockers,
              filesTouched: args.filesTouched,
              notes: args.notes,
            },
            args.snapshotName,
          )
          messagesSinceLastSave = 0
          isDirty = false
          return JSON.stringify(result, null, 2)
        },
      }),

      checkpoint_load: tool({
        description: "Load full current checkpoint state.",
        args: {},
        async execute() {
          const data = await load()
          return JSON.stringify(data ?? { exists: false }, null, 2)
        },
      }),

      checkpoint_status: tool({
        description:
          "Quick status check — whether a checkpoint exists and its current status.",
        args: {},
        async execute() {
          const data = await load()
          if (!data) {
            return JSON.stringify({ exists: false }, null, 2)
          }
          return JSON.stringify(
            {
              exists: true,
              updatedAt: data.updatedAt,
              title: data.task?.title ?? null,
              status: data.task?.status ?? null,
              completedSteps: data.completedSteps?.length ?? 0,
              nextSteps: data.nextSteps?.length ?? 0,
              blockers: data.blockers?.length ?? 0,
            },
            null,
            2,
          )
        },
      }),

      checkpoint_clear: tool({
        description: "Delete the checkpoint file entirely.",
        args: {},
        async execute() {
          await unlink(file).catch(() => {})
          return JSON.stringify({ cleared: true }, null, 2)
        },
      }),

      checkpoint_list: tool({
        description:
          "List all snapshots in checkpoint history, newest first. Returns name, savedAt, task title and status for each entry. Use checkpoint_load_snapshot to inspect full data, checkpoint_restore_snapshot to restore.",
        args: {},
        async execute() {
          const history = await loadHistory()
          if (!history.snapshots || history.snapshots.length === 0) {
            return JSON.stringify({ snapshots: [], count: 0 }, null, 2)
          }
          const reversed = [...history.snapshots].reverse()
          const list = reversed.map((entry, idx) => ({
            index: idx,
            name: entry.name,
            savedAt: entry.savedAt,
            title: entry.data.task?.title ?? null,
            status: entry.data.task?.status ?? null,
          }))
          return JSON.stringify(
            { snapshots: list, count: history.snapshots.length },
            null,
            2,
          )
        },
      }),

      checkpoint_load_snapshot: tool({
        description:
          "Load full data for a specific named snapshot from history. Read-only — does NOT overwrite live checkpoint.json. Use checkpoint_restore_snapshot to promote a snapshot to live state.",
        args: {
          name: tool.schema.string(),
        },
        async execute(args) {
          const history = await loadHistory()
          const entry = history.snapshots.find((s) => s.name === args.name)
          if (!entry) {
            return JSON.stringify(
              {
                error: "Snapshot not found",
                name: args.name,
                available: history.snapshots.map((s) => s.name),
              },
              null,
              2,
            )
          }
          return JSON.stringify(entry.data, null, 2)
        },
      }),

      checkpoint_restore_snapshot: tool({
        description:
          "Restore a named snapshot as the live checkpoint state. Before overwriting, the current live state is automatically saved as a snapshot named 'pre-restore-{timestamp}' so you can undo.",
        args: {
          name: tool.schema.string(),
        },
        async execute(args) {
          const liveState = await load()
          if (liveState) {
            const preRestoreName = `pre-restore-${Date.now()}`
            const history = await loadHistory()
            history.snapshots.push({
              name: preRestoreName,
              savedAt: new Date().toISOString(),
              data: JSON.parse(JSON.stringify(liveState)),
            })
            if (history.snapshots.length > MAX_HISTORY) {
              history.snapshots = history.snapshots.slice(-MAX_HISTORY)
            }
            await saveHistory(history)

            const targetHistory = await loadHistory()
            const target = targetHistory.snapshots.find(
              (s) => s.name === args.name,
            )
            if (!target) {
              return JSON.stringify(
                { error: "Snapshot not found", name: args.name },
                null,
                2,
              )
            }
            await save(target.data)
            return JSON.stringify(
              {
                restored: true,
                name: args.name,
                undoSnapshot: preRestoreName,
              },
              null,
              2,
            )
          }

          const history = await loadHistory()
          const entry = history.snapshots.find((s) => s.name === args.name)
          if (!entry) {
            return JSON.stringify(
              { error: "Snapshot not found", name: args.name },
              null,
              2,
            )
          }
          await save(entry.data)
          return JSON.stringify(
            { restored: true, name: args.name, undoSnapshot: null },
            null,
            2,
          )
        },
      }),
    },

    "experimental.session.compacting": async (_input, output) => {
      const state = await load()
      if (!state) return

      const hash = JSON.stringify(state)
      if (hash === lastInjectedHash) return
      lastInjectedHash = hash

      output.context.push(`
## CHECKPOINT STATE

\`\`\`json
${JSON.stringify(state, null, 2)}
\`\`\`

Continue from this state.
Do not redo completed work.
Prioritize nextSteps.
`)
    },

    event: async ({ event }) => {
      if (event.type !== "session.compacted") return

      const existing = await load()
      if (existing) {
        await save({})
        await ctx.client.app.log({
          body: {
            service: "checkpoint",
            level: "info",
            message:
              "Auto-snapshot on session.compacted (existing state re-saved)",
          },
        })
      } else {
        await save({
          task: {
            title: "Auto-synthesized checkpoint",
            status: "in_progress",
          },
          summary:
            "Session compacted without prior checkpoint_save call. State synthesized automatically.",
          notes: [
            "Auto-generated on session.compacted — agent did not call checkpoint_save before compaction.",
          ],
        })
        await ctx.client.app.log({
          body: {
            service: "checkpoint",
            level: "warn",
            message:
              "Auto-snapshot on session.compacted (synthesized — no prior save found)",
          },
        })
      }
    },

    "chat.message": async (_ctx, _output) => {
      messagesSinceLastSave++
      if (messagesSinceLastSave >= AUTOSAVE_EVERY_N_MESSAGES) {
        const existing = await load()
        if (existing) {
          await save(existing)
          messagesSinceLastSave = 0
          await ctx.client.app.log({
            body: {
              service: "checkpoint",
              level: "info",
              message: `Auto-save triggered after ${AUTOSAVE_EVERY_N_MESSAGES} messages`,
              extra: { updatedAt: existing.updatedAt },
            },
          })
        } else {
          messagesSinceLastSave = 0
        }
      }
    },
  }
}
